#!/bin/bash
set -e

echo "=========================================="
echo "Moodle Docker Entrypoint Script"
echo "=========================================="

# Wait for database to be ready
echo "Waiting for database to be ready..."
MAX_RETRIES=60
RETRY_COUNT=0

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if mysql -h"${MOODLE_DATABASE_HOST}" -P"${MOODLE_DATABASE_PORT:-3306}" -u"${MOODLE_DATABASE_USER}" -p"${MOODLE_DATABASE_PASSWORD}" "${MOODLE_DATABASE_NAME}" -e "SELECT 1" 2>/dev/null; then
        echo "Database is ready!"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    echo "Database not ready yet, waiting... (attempt $RETRY_COUNT/$MAX_RETRIES)"
    sleep 3
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo "ERROR: Could not connect to database after $MAX_RETRIES attempts!"
    echo "Please check:"
    echo "  - MySQL container is running: docker compose logs mysql"
    echo "  - Database credentials are correct"
    echo "  - Network connectivity between containers"
    exit 1
fi

# Set proper permissions for moodledata
echo "Setting permissions for moodledata directory..."
mkdir -p /var/www/moodledata
chown -R www-data:www-data /var/www/moodledata
chmod -R 0770 /var/www/moodledata

# Check if config.php exists in base directory
CONFIG_FILE="/var/www/html/config.php"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "=========================================="
    echo "Creating config.php..."
    echo "=========================================="
    
    cat > "$CONFIG_FILE" <<EOF
<?php
///////////////////////////////////////////////////////////////////////////
//                                                                       //
// Moodle configuration file                                             //
//                                                                       //
// Auto-generated by Docker                                              //
//                                                                       //
///////////////////////////////////////////////////////////////////////////

unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

//=========================================================================
// 1. DATABASE SETUP
//=========================================================================
\$CFG->dbtype    = '${MOODLE_DATABASE_TYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${MOODLE_DATABASE_HOST}';
\$CFG->dbname    = '${MOODLE_DATABASE_NAME}';
\$CFG->dbuser    = '${MOODLE_DATABASE_USER}';
\$CFG->dbpass    = '${MOODLE_DATABASE_PASSWORD}';
\$CFG->prefix    = '${MOODLE_DATABASE_PREFIX}';
\$CFG->dboptions = [
    'dbpersist' => false,
    'dbsocket'  => false,
    'dbport'    => '${MOODLE_DATABASE_PORT}',
    'dbcollation' => 'utf8mb4_unicode_ci',
];

//=========================================================================
// 2. WEB SITE LOCATION
//=========================================================================
\$CFG->wwwroot   = '${MOODLE_WWWROOT:-http://localhost:9000}';

//=========================================================================
// 3. DATA FILES LOCATION
//=========================================================================
\$CFG->dataroot  = '/var/www/moodledata';

//=========================================================================
// 4. ROUTER CONFIGURATION
//=========================================================================
\$CFG->routerconfigured = false;

//=========================================================================
// 5. OTHER SETTINGS
//=========================================================================
// Force a debugging mode regardless the settings in the site administration
// @error_reporting(E_ALL | E_STRICT); // NOT FOR PRODUCTION SERVERS!
// @ini_set('display_errors', '1');    // NOT FOR PRODUCTION SERVERS!
// \$CFG->debug = (E_ALL | E_STRICT);   // === DEBUG_DEVELOPER - NOT FOR PRODUCTION SERVERS!
// \$CFG->debugdisplay = 1;              // NOT FOR PRODUCTION SERVERS!

// Prevent core_string_manager application caching
// \$CFG->langstringcache = false; // NOT FOR PRODUCTION SERVERS!

// Prevent JS caching
// \$CFG->cachejs = false; // NOT FOR PRODUCTION SERVERS!

// Prevent Theme caching
// \$CFG->themedesignermode = true; // NOT FOR PRODUCTION SERVERS!

// Disable SSO by default in Docker
\$CFG->admin = 'admin';

// Performance: Set to true in production
\$CFG->cachejs = true;
\$CFG->yuicomboloading = true;

// Email configuration (using MailHog SMTP server)
\$CFG->smtphosts = 'mailhog:1025';
\$CFG->smtpsecure = '';
\$CFG->smtpauthtype = '';
\$CFG->smtpuser = '';
\$CFG->smtppass = '';
\$CFG->noreplyaddress = 'noreply@localhost';

require_once(__DIR__ . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!
EOF

    chmod 644 "$CONFIG_FILE"
    chown root:www-data "$CONFIG_FILE"
    
    echo "config.php created successfully!"
else
    echo "config.php already exists, skipping creation."
fi

# Check if Moodle is already installed
if [ ! -f "/var/www/moodledata/.moodle_installed" ]; then
    echo "=========================================="
    echo "Running Moodle CLI installation..."
    echo "=========================================="
    
    # Give the database a bit more time to fully initialize
    sleep 5
    
    # Run Moodle CLI installer
    php /var/www/html/public/admin/cli/install.php \
        --chmod=2777 \
        --lang=en \
        --wwwroot="${MOODLE_WWWROOT:-http://localhost:9000}" \
        --dataroot=/var/www/moodledata \
        --dbtype="${MOODLE_DATABASE_TYPE}" \
        --dbhost="${MOODLE_DATABASE_HOST}" \
        --dbname="${MOODLE_DATABASE_NAME}" \
        --dbuser="${MOODLE_DATABASE_USER}" \
        --dbpass="${MOODLE_DATABASE_PASSWORD}" \
        --dbport="${MOODLE_DATABASE_PORT}" \
        --prefix="${MOODLE_DATABASE_PREFIX}" \
        --fullname="${MOODLE_SITE_FULLNAME:-Moodle Site}" \
        --shortname="${MOODLE_SITE_SHORTNAME:-Moodle}" \
        --summary="${MOODLE_SITE_SUMMARY:-Moodle Site}" \
        --adminuser="${MOODLE_ADMIN_USER:-admin}" \
        --adminpass="${MOODLE_ADMIN_PASSWORD:-Admin@123}" \
        --adminemail="${MOODLE_ADMIN_EMAIL:-admin@example.com}" \
        --non-interactive \
        --agree-license || {
        echo "=========================================="
        echo "WARNING: Moodle installation may have failed or already exists"
        echo "This is normal if you're restarting the container"
        echo "=========================================="
    }
    
    # Mark installation as complete
    touch /var/www/moodledata/.moodle_installed
    
    echo "=========================================="
    echo "Moodle installation completed!"
    echo "=========================================="
    echo "Admin credentials:"
    echo "  Username: ${MOODLE_ADMIN_USER:-admin}"
    echo "  Password: ${MOODLE_ADMIN_PASSWORD:-Admin@123}"
    echo "  Email: ${MOODLE_ADMIN_EMAIL:-admin@example.com}"
    echo "=========================================="
else
    echo "Moodle is already installed, skipping installation."
    
    # Run upgrade in case of version changes
    echo "Checking for upgrades..."
    php /var/www/html/public/admin/cli/upgrade.php --non-interactive || true
fi

# Ensure proper permissions after installation
echo "Finalizing permissions..."
chown -R www-data:www-data /var/www/moodledata
chmod -R 0770 /var/www/moodledata

# Make sure code is not writable by web server (security)
find /var/www/html -type f -exec chmod 0644 {} \; 2>/dev/null || true
find /var/www/html -type d -exec chmod 0755 {} \; 2>/dev/null || true
chown -R root:www-data /var/www/html 2>/dev/null || true

# Make config.php readable by web server but not writable
chmod 644 "$CONFIG_FILE" 2>/dev/null || true
chown root:www-data "$CONFIG_FILE" 2>/dev/null || true

echo "=========================================="
echo "Starting Moodle services..."
echo "=========================================="
echo "Web Interface: ${MOODLE_WWWROOT:-http://localhost:9000}"
echo "MailHog (email testing): http://localhost:9003"
echo "phpMyAdmin: http://localhost:9002"
echo "=========================================="

# Execute the main command (supervisord)
exec "$@"
